import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` min-h-svh flex flex-col ${inter.className}`}>
        <header className="bg-black text-white">
        <Link href='/'>Home</Link>
        </header>
        <main className="flex-grow ">
          {children}
        </main>
        <footer className="bg-black text-white mt-auto">This is the footer </footer>
      </body>
    </html>
  );
}
